#!/usr/bin/env bash
echo "% Automatically generated by git_information.sh"
echo "`git status --porcelain 2>/dev/null| wc -l | tr -d [:blank:]`"' files different from commit '"`git rev-parse --short HEAD`"' from '"`git log -1 --format=%ad --date=iso`"