#!/usr/bin/env bash
echo "% Automatically generated by git_information.sh"
echo '\newcommand{\gitRevision}{'"`git log -1 --format=%H`"'}'
echo '\newcommand{\gitRevisionDate}{'"`git log -1 --format=%ad --date=iso`"'}'
echo '\newcommand{\gitDirtyFiles}{'"`git status --porcelain 2>/dev/null| wc -l | tr -d [:blank:]`"'}'
echo '\newcommand{\gitInfo}{\gitDirtyFiles\ files different from commit \gitRevision\ from \gitRevisionDate}'