#!/usr/bin/env bash

echo -n "Making latest version..."
pushd "$(git rev-parse --show-toplevel)" > /dev/null
make DRAFT=1 master.pdf 1>/dev/null 2>/dev/null
RESULT=$?
popd > /dev/null

if [[ $RESULT -ne 0 ]]; then
    echo "failed."
    exit 1
fi

echo "success!"
exit 0