#!/usr/bin/env bash

STASH_NAME="pre-commit-$(date +%s)"
LOG=".git-pre-commit-hook.log"
N=10
git stash push --keep-index --include-untracked $STASH_NAME

echo -n "Making based on latest commit..."

pushd "$(git rev-parse --show-toplevel)" > /dev/null
make master.pdf > "$LOG"
RESULT=$?
popd > /dev/null

LATEST_STASH_Q=$(git stash list | head -n 1 | grep -c "$STASH_NAME")

if [[ $LATEST_STASH_Q == "1" ]]; then
    git stash pop
fi

if [[ $RESULT -ne 0 ]]; then
    echo "failed."
    echo "Please ensure \`make master.pdf\` succeeds before committing."
    echo "See $LOG for more details"
    echo "The last $N lines of the log are:"
    tail -n $N "$LOG"
    exit 1
fi

echo "success!"
exit 0