name: Build LaTeX DIFF
on: [pull_request]
env:
  target: master
jobs:
  build-diff-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Extract base name
        shell: bash
        run: echo "##[set-output name=branch;]$(base_ref=${{ github.base_ref }}; with_slashes=${base_ref#refs/heads/}; echo ${with_slashes//\//-})"
        id: extract_base
      - name: Extract head name
        shell: bash
        run: echo "##[set-output name=branch;]$(head_ref=${{ github.head_ref }}; with_slashes=${head_ref#refs/heads/}; echo ${with_slashes//\//-})"
        id: extract_head
      - name: Create DIFF file name
        id: diff
        shell: bash
        run: echo "##[set-output name=file;]$(echo ${{ env.target}}-${{ steps.extract_head.outputs.branch }}-vs-${{ steps.extract_base.outputs.branch }}.pdf)"
      - name: Check DIFF file name
        shell: bash
        run: echo ${{ steps.diff.outputs.file }} >&2
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get BASE branch
        run:  git checkout ${{ github.base_ref }}
      - name: Get HEAD branch
        run:  git checkout ${{ github.head_ref }}
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          compiler:  make
          args: VERBOSE=1 DIFF=1 OLD=${{ github.base_ref }} NEW=${{ github.head_ref}} TARGET=${{ env.target }}
          root_file: ${{ env.target }}.pdf
      - name: Copy to SHA-suffixed file

        run: cp ${{ env.target}}.pdf ${{ steps.diff.outputs.file }}
      - name: Store compiled PDF artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.diff.outputs.file }}
          path: ${{ steps.diff.outputs.file }}
          if-no-files-found: error
