name: Build LaTeX DIFF
on: [pull_request]
env:
  target: master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          compiler:  make
          args: VERBOSE=1 DIFF=1 OLD=${{ github.base_ref }} NEW=${{ github.head_ref}} TARGET=${{ env.target }}
          root_file: ${{ env.target }}.pdf
      - name: Copy to SHA-suffixed file

        run: cp ${{ env.target}}.pdf ${{ env.target}}-${{ github.head_ref }}-vs-${{ github.base_ref }}.pdf
      - name: Store compiled PDF artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.target}}-${{ github.head_ref }}-vs-${{ github.base_ref }}.pdf
          path: ${{ env.target}}-${{ github.head_ref }}-vs-${{ github.base_ref }}.pdf
          if-no-files-found: error
